- name: Deprovision Infrastructure with kcli
  hosts: localhost
  vars:
    plan: prout
  tasks:
    - import_role:
        name: karmab.kcli-modules
    - name: Delete plan
      kvirt_plan: 
        name: "{{ plan }}"
        state: absent
